seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
  gpus: -1
  accelerator: ddp
  max_epochs: 300
  deterministic: true
  check_val_every_n_epoch: 10
  #resume_from_checkpoint: 'lightning_logs/version_6/checkpoints/epoch=57-step=5161-val_ExpRate=0.5702.ckpt'
model:
  d_model: 256
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dc: 32
  dropout: 0.3
  vocab_size: 112  # 107 + 5
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 0.08
  patience: 10
  dynamic_weight: false

data:
  folder: data/qa-hme
  test_folder: test
  max_size: 480000
  scale_to_limit: false
  train_batch_size: 16
  eval_batch_size: 8
  num_workers: 8
  scale_aug: false
